import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ScrollProvider } from "./context/ScrollContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "AARUUSH App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // --- ADD THE PROP TO THE <html> TAG ---
    <html lang="en" suppressHydrationWarning={true}>
      <body className={inter.className}>
        <ScrollProvider>{children}</ScrollProvider>
      </body>
    </html>
  );
}
